name: Deploy

on:
  push:
    branches:
      - master

concurrency: production_deploy

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: '6.24.4'
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'pnpm'
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build website
        run: pnpm build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: pnpm deploy
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_CF_DIST_ID: ${{ secrets.AWS_CF_DIST_ID }}
